# 服务配置，设置gin的运行模式、默认的HTTP监听端口、允许读取和写入的最大持续时间
Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
# 应用配置，设置默认每页数量、所允许的最大每页数量、以及默认的应用日志存储路径
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
# 数据库配置，主要是连接实例所需的基础参数
Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 192.168.0.188:3306
  DBName: go
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30